#!/bin/bash

# Simple shell script to start up MediaWiki + containers.
# Alternative to docker-compose, with automatic docker subnet detection to make
# this work on jessie or sid.

if [ -d /var/lib/mediawiki-containers \
    -a -f /var/lib/mediawiki-containers/config ]; then
    source /var/lib/mediawiki-containers/config
fi

# Set up defaults
if [ -z "$MEDIAWIKI_DOMAIN" ]; then
    # Ewww..
    MEDIAWIKI_DOMAIN="localhost"
fi

start () {
    set -e
    echo
    echo "Starting DNS container.."
    docker pull tonistiigi/dnsdock
    docker run -d \
        --name=dnsdock \
        -v /var/run/docker.sock:/run/docker.sock \
        tonistiigi/dnsdock
    DNS=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' dnsdock)

    echo
    echo "Starting mysql(mariadb) container.."
    docker pull mariadb
    docker run -d \
        --name=mysql \
        -e SERVICE_NAME=mysql \
        -v /var/lib/mediawiki-containers/mediawiki-mysql:/var/lib/mysql:rw \
        -e MYSQL_ROOT_PASSWORD=password \
        --dns "$DNS" \
        mariadb

    echo
    echo "Starting mediawiki container.."
    docker pull wikimedia/mediawiki
    docker run -d \
        --name=mediawiki \
        -v `pwd`/conf/mediawiki:/conf:ro \
        -v /var/lib/mediawiki-containers/mediawiki-core:/data:rw \
        -e MEDIAWIKI_SITE_SERVER="//$MEDIAWIKI_DOMAIN" \
        -e MEDIAWIKI_SITE_NAME=MediaWiki \
        -e MEDIAWIKI_SITE_LANG=en \
        -e MEDIAWIKI_ADMIN_USER=admin \
        -e MEDIAWIKI_ADMIN_PASS=rosebud \
        -e MEDIAWIKI_UPDATE=true \
        -e MEDIAWIKI_DB_USER=root \
        -e MEDIAWIKI_DB_HOST=mysql.docker \
        -e MEDIAWIKI_DB_PASSWORD=password \
        -e MEDIAWIKI_RESTBASE_URL=http://mediawiki-node-services.docker:7231/localhost/v1 \
        --dns "$DNS" \
        -p 80:80 \
        wikimedia/mediawiki

    echo
    echo "Starting mediawiki-node-services container.."
    docker pull wikimedia/mediawiki-node-services
    docker run -d \
        --name=mediawiki-node-services \
        -v /var/lib/mediawiki-containers/node-services:/data \
        -e MEDIAWIKI_API_URL=http://mediawiki.docker/api.php \
        --dns "$DNS" \
        -p 8142:8142 \
        wikimedia/mediawiki-node-services

    # Follow the mediawiki container logs
    docker logs -f mediawiki
}

stop () {
    echo "Stopping and deleting all containers.."
    # The containers themselves are stateless (all data is stored in
    # /var/lib/mediawiki-containers), so always nuke them.
    docker rm -f mediawiki
    docker rm -f mediawiki-node-services
    docker rm -f mysql
    docker rm -f dnsdock
}


if [ -z "$1" ];then
    echo "Welcome to containerized MediaWiki."
    echo "Usage: $0 [start|stop|restart]"
    exit 1
elif [ "$1" == "stop" ]; then
    stop
elif [ "$1" == "start" ]; then
    start
elif [ "$1" == "restart" ]; then
    stop
    start
else
    echo "Invalid parameter: $1"
    exit 1
fi
