#!/bin/bash

# Simple shell script to start up MediaWiki + containers.
# Alternative to docker-compose, with automatic docker subnet detection to make
# this work on jessie or sid.

BASEDIR=/srv/mediawiki-containers
DATADIR="$BASEDIR/data"

if [ -d $BASEDIR -a -f $BASEDIR/config ]; then
    source $BASEDIR/config
fi

# Set up defaults
if [ -z "$MEDIAWIKI_DOMAIN" ]; then
    # Ewww..
    MEDIAWIKI_DOMAIN="localhost"
fi

start () {
    set -e
    echo
    echo "Starting DNS container.."
    docker pull tonistiigi/dnsdock
    docker run -d \
        --name=dnsdock \
        -v /var/run/docker.sock:/run/docker.sock \
        tonistiigi/dnsdock
    DNS=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' dnsdock)

    echo
    echo "Starting mysql(mariadb) container.."
    docker pull mariadb
    docker run -d \
        --name=mysql \
        -e SERVICE_NAME=mysql \
        -v $DATADIR/mediawiki-mysql:/var/lib/mysql:rw \
        -e MYSQL_ROOT_PASSWORD=password \
        --dns "$DNS" \
        mariadb

    echo
    echo "Starting mediawiki container.."
    docker pull wikimedia/mediawiki
    docker run -d \
        --name=mediawiki \
        -v `pwd`/conf/mediawiki:/conf:ro \
        -v $DATADIR/mediawiki-core:/data:rw \
        -e MEDIAWIKI_SITE_SERVER="//$MEDIAWIKI_DOMAIN" \
        -e MEDIAWIKI_SITE_NAME=MediaWiki \
        -e MEDIAWIKI_SITE_LANG=en \
        -e MEDIAWIKI_ADMIN_USER=admin \
        -e MEDIAWIKI_ADMIN_PASS=rosebud \
        -e MEDIAWIKI_UPDATE=true \
        -e MEDIAWIKI_DB_USER=root \
        -e MEDIAWIKI_DB_HOST=mysql.docker \
        -e MEDIAWIKI_DB_PASSWORD=password \
        -e MEDIAWIKI_RESTBASE_URL=http://mediawiki-node-services.docker:7231/localhost/v1 \
        --dns "$DNS" \
        -p 80:80 \
        wikimedia/mediawiki

    echo
    echo "Starting mediawiki-node-services container.."
    docker pull wikimedia/mediawiki-node-services
    docker run -d \
        --name=mediawiki-node-services \
        -v $DATADIR/node-services:/data \
        -e MEDIAWIKI_API_URL=http://mediawiki.docker/api.php \
        --dns "$DNS" \
        -p 8142:8142 \
        wikimedia/mediawiki-node-services

    # Follow the mediawiki container logs
    docker logs -f mediawiki
}

stop () {
    echo "Stopping and deleting all containers.."
    # The containers themselves are stateless (all data is stored in
    # /var/lib/mediawiki-containers), so always nuke them.
    docker rm -f mediawiki 2>/dev/null
    docker rm -f mediawiki-node-services 2>/dev/null
    docker rm -f mysql 2>/dev/null
    docker rm -f dnsdock 2>/dev/null
}

install_git() {
    if ! hash git 2>/dev/null;then
        echo "Installing git.."
        apt-get install -y git
    else
        echo "[OK] Found git."
    fi
}

check_out_mediawiki_containers() {
    if [ ! -d "$BASEDIR" ];then
        echo "Cloning mediawiki-containers to $BASEDIR.."
        git clone https://github.com/wikimedia/mediawiki-containers.git "$BASEDIR"
    else
        cd "$BASEDIR"
        echo "Updating $BASEDIR.."
        git pull
    fi
    cd "$BASEDIR"
}

usage() {
    echo "Usage: $0 [start|stop|restart|install]"
}

install() {
    while true; do
        read -p "Would you proceed to install / update mediawiki-containers? (y/n): " \
            yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) echo "Okay, aborting."; exit 1;;
            * ) echo "Please answer 'y' or 'n'.";;
        esac
    done
    # User answered 'y'; proceed to install.

    # Make sure we have git.
    install_git

    # Clone / update the mediawiki-containers repository.
    check_out_mediawiki_containers

    cd $BASEDIR
    
    source ./lib/install.sh
    do_install

    echo "Starting mediawiki-containers.."
    stop
    start

    echo "Starting up containers.."
    echo "Your wiki should shortly be available at http://$MEDIAWIKI_DOMAIN/."
    echo 'To follow the startup progress, run `journalctl -f`.'
    echo "[OK] All done."
}

if [ "$1" == "stop" ]; then
    stop
elif [ "$1" == "start" ]; then
    start
elif [ "$1" == "restart" ]; then
    stop
    start
elif [ -z "$1" -o "$1" == "install" ]; then
    echo "Welcome to MediaWiki-containers!"
    echo
    install
else
    echo "Invalid parameter $1"
    usage
    exit 1
fi

